### ISSUE TITLE
Several setup questions

### ISSUE THREAD

**Issue by flexgrip** [a1comms/GaeFlexSupportL5#44]
Hello again,

I was going to use your package solely so that I can get Cloud Tasks to work as a queue driver. But then I had a bunch of questions about how I might use other portions of it. So I'm going to place these below. If you have time, I'd love to know what you think. I noticed other tickets about example configurations and cloud build configs. Maybe this can help clear those up. I could even PR some to you if you think it would help.

### Current setup
You should know I already have an existing Laravel 5.8 installation on GAE standard. And I would prefer not to use flex/docker. I do not use cloud build and I could not figure out how to get cloud build to compile my node assets while still using GAE Standard.

**What I have working:**
- [x] Vanilla deploy without cloud-build
- [x] Cloud SQL as DB
- [x] Stack driver logging (but there don't seem to be many logs or maybe its not working)

**What I don't have working:**
- [x] Task queues using cloud tasks
- [ ] Blade view compiler (not sure what is getting compiled, if anything)
- [ ] I have to pre-build my JS before deploying

## Questions
1. How do you currently compile node/js assets for a deployment? I have to run `yarn run production` before deploying JS changes
2. Since I am not doing anything regarding blade view compilation, does that mean that its just running everything at runtime? Not sure how its currently working since I haven't touched the blade compiling
3. How are you running cron? I setup a cron.yaml and pointed it at an endpoint, but it doesn't really seem to do much.

Thanks!

**Comment by flexgrip** [comment]
**Update**...

I've installed the package and was able to get new tasks onto the Cloud Tasks queue. However, when they run, I'm getting a 404. It looks like cloud tasks is trying to send the request to whatever I set as the gae driver's -> `url` in `config/queue.php`.

I checked the package and I don't see that it's registering any routes. Should I be creating a route to accept the requests from Cloud Tasks? I don't see any type of handler that can accept those requests inside the package.

If I have to make a route/handler for each job, that sort of defeats the purpose. So perhaps I'm missing something.

**Comment by flexgrip** [comment]
So I’ve tried a few ways to make an endpoint for cloud tasks to run my jobs. The old docs that this package was based on just said to run the `Queue::marshal()` method. But that has been removed in >= L5.2. I see you have a marshal function, but I don’t know how to route the task to there properly. I tried it but it was missing arguments needed to run it.

Thanks again!

**Comment by iamacarpet** [comment]
Not ignoring this on purpose, massively busy time at work this week, so will give you a shout when it calms down a bit.

Do need to write some docs for queues & Cloud Build, although for queues done Laravel’s way, we only use it on one project and for everything else, we just queue standard HTTP requests via the TaskQueue interface in Integrations.

There’s a good doc for the view compiler in the docs folder, might get you somewhere on the meantime.

**Comment by iamacarpet** [comment]
**Stack driver logging (but there don't seem to be many logs or maybe its not working)**

If you are logging things from the app but you can't see them, perhaps they aren't selected to display? Have you expanded this bit in Stackdriver Logging (see screenshot)? Application logs go to `app.log` by default and exceptions to go a log called `exceptions` to be picked up by "Error Reporting".

![screenshot 1567433257](https://user-images.githubusercontent.com/1333857/64872056-60b06480-d63e-11e9-9185-8605536fdb97.jpg)

Also worth noting that the logs don't always aggregate properly for display under the request entry, but this is just a display bug in Stackdriver Logging, they should still be attributable to a specific request if you have one you are interested in using the "trace" identifier.

![screenshot 1567433258](https://user-images.githubusercontent.com/1333857/64872442-21364800-d63f-11e9-989d-3cd6d76211d0.jpg)

Try finding the request, clicking the trace identifier, then "show matching entries" (see screenshot above).

Then in the advanced filter, remove the line that limits it to the request log, so it goes from this:

![screenshot 1567433259](https://user-images.githubusercontent.com/1333857/64872767-aa4d7f00-d63f-11e9-91b7-25479391ad57.jpg)

to this:

![screenshot 1567433260](https://user-images.githubusercontent.com/1333857/64872781-b0dbf680-d63f-11e9-823a-4aa941a17f45.jpg)

and search... any better?

**Comment by iamacarpet** [comment]
**Task Queue (the Laravel way)**

Just checked our existing project that uses this and in `routes/web.php`, we've got:

```php
// Cloud Task inbound route for async jobs when driver set to 'gae'.
Route::post('tasks', array('middleware' => 'gae.task', 'as' => 'tasks',
function()
{
	return Queue::marshal();
}));
```

Ignore the middleware, it is just doing some authentication to make sure it is legitimately coming from App Engine internally (can validate and share these later), however bare that in mind that you may need to explicitly allow the requests if you are using authentication guards elsewhere.

And in `config/queue.php`:

```php
    'connections' => [

        'gae' => array(
			'driver'	=> 'gae',
			'queue'		=> 'default',
			'url'		=> '/tasks',
			'encrypt'	=> true,
		),
```

The only other bits of config I can see for it are, from `.env`:

```
QUEUE_DRIVER=gae
```

And from `config/app.php`:

```php
    'providers' => [
        A1comms\GaeSupportLaravel\Queue\QueueServiceProvider::class,
```

If this isn't working, I think the tasks endpoint should log, so looking in the logs might be a good place to start.

Also, it looks like this expects there to be a pre-existing queue called "default" ready to push into; have you already created on via "Cloud Tasks" in Cloud Console?

**Comment by flexgrip** [comment]
Thanks so much. My logs look the same as yours, so I guess my custom driver is working.

Regarding the queues, I’ll use the middleware to confirm the authenticity of the requests, however, that must be a super old project because the marshal method was removed from `Queue` in Laravel 5.2.

I’m just going to try having the route issue the `queue:work` artisan command without running in daemon mode. I just don’t know how the app would know which task to run based off of the request. I guess it would just run them in order. Which could work.

**Comment by iamacarpet** [comment]
Just double checked and it's definately L5.5

Not sure if we inadvertently added that method back?

Or actually, something comes to mind that it was removed from the documentation, but not actually removed from their code?

Either way, give it a try - this project is actively using it and a recent composer update didn't break anything, so hopefully you'll be surprised :).

**Comment by flexgrip** [comment]
You were totally right. I forgot that I was replacing the Illuminate instance of `Queue` with your custom implementation. Hopefully since I'm on L5.8 that doesn't mean I'm missing anything vital. But I am now able to queue tasks and run them.

Thanks you so so much!

**Comment by iamacarpet** [comment]
@flexgrip , I had the Cloud Build docs on my to-do list too, so tried to do a basic version of them today.

Please see `docs/cloudbuild.md`, feedback is welcome.

I need to properly document how to store secrets encrypted with KMS for decryption at deploy time, so they aren't saved plain in the repo, but I need to dig the commands out again myself.

**Comment by iamacarpet** [comment]
Just noticed your actual questions, sorry about missing those before. Hope this helps a little...

> How do you currently compile node/js assets for a deployment? I have to run yarn run production before deploying JS changes

You’ll see in the Cloud Build examples that we seem to be running ‘npm run production’ before deploying via ‘gcloud’.

I haven’t been massively involved with this bit, but I think I’ve heard the app developers say they are using what ever the recommended tooling is for Laravel 5.5... Laravel Mix maybe?

> Since I am not doing anything regarding blade view compilation, does that mean that its just running everything at runtime? Not sure how its currently working since I haven't touched the blade compiling.

Not sure if you’ve read the doc on the blade compiler, but yes if you haven’t enabled it, it’ll probably be compiling at runtime into “/tmp”, as that’s the only writable folder on this runtime.

It’s mostly a performance win with it enabled, not so much on the compilation itself, but not having to recheck the file system a number of times each time any view is rendered, since we know once deployed, they can’t change.

Can’t promise it’ll work if you are using Laravel 5.8 though, as we are targeting 5.5 and I know there is a bit difference in how we had to implement it between 5.1 and 5.5, so there may be a big difference upwards to 5.8 too.

> How are you running cron? I setup a cron.yaml and pointed it at an endpoint, but it doesn't really seem to do much.

Pretty much how you describe, cron.yaml entry with a route in Laravel, which seems to work pretty well for us - this is also pretty much how we do queued jobs, rather than using the Laravel native queue driver, as it’s way easier to debug this way.

When you say it doesn’t do much, you don’t think it is reaching your controller?
